version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: adan 
      POSTGRES_PASSWORD: queguapo
      POSTGRES_DB: nestdb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5499:5432" 